### PR TITLE
Search Feature Done, need some changes to color combination of the page

### PR DESCRIPTION
**Pull request by Rohit-1997**
Boys,

Check the DB feature and I think there should be a change in the color combination of the page. we will work together on it tomorrow.
@vamshi-kura @golipranayreddy

### CODE REVIEW

**Comment by Rohit-1997** [comment]
Adding screenshot

Screenshot from 2020-04-22 01-22-15

**Comment by ashishk144** [comment]
The screenshot posted is before or after the search? If it's after the search, you only display the search box when the user is logged in right?

**Comment by Rohit-1997** [comment]
Yes bro, The search box is displayed only after the user logs in.

**Comment by ashishk144** [comment]
Delete create.py file. Add .gitignore file. Admin page should display users in descending order of timestamp.

**Comment by Rohit-1997** [comment]
yeah bro, I will change the order. But why delete the create.py file?

**Comment by Rohit-1997** [comment]
Bro, I have deleted the create.py file, made changes to the admin page, and also added git ignore. Please check and let me know if there are any other changes

**Pull request merged**
